apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-ubpkcgye
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/go-ubpkcgye:d5f8db0f8fccdc8de8a319f41d9771eaf2882219@sha256:0d032f6456797f6d1df122caa3a23737383a97dce78ce2fd89bb93c96df1ba95
          name: container-image
